#!/bin/bash

set -e

if [[ "$#" != "2" ]]; then
  echo "Usage: autocrop input.mov output.mov"
  exit 1
fi

input="$1"
output="$2"
tmpdir="tmp-$$"
ffmpeg_opts="-hide_banner -loglevel 0 -nostats"

mkdir "$tmpdir"

read -p "Use first frame to figure out coordinates? (Y/n): " confirm
if [[ $confirm == "" || $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
  echo "Exporting first frame..."

  frame="$tmpdir/frame.png"
  ffmpeg $ffmpeg_opts -i "$input" -vframes 1 -f image2 "$frame"
  open "$frame"
fi

read -p "Input width:height > " wh
read -p "Input left:top > " lt

ffmpeg $ffmpeg_opts -i "$input" -vf "crop=${wh}:${lt}" "$output"

read -p "Do you want a gif? (y/N): " confirm

if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
  mv "$output" "$tmpdir/$output"

  cropped="$tmpdir/$output"
  gifname=$(basename -- "$output")
  gifname="${gifname%.*}.gif"

  echo "Generating palette..."
  palette="$tmpdir/palette.png"
  ffmpeg $ffmpeg_opts -i "$cropped" -vf "fps=15,scale=320:-1:flags=lanczos,palettegen" "$palette"

  echo "Generating gif..."
  ffmpeg $ffmpeg_opts -i "$cropped" -i $palette -filter_complex "fps=15,scale=400:-1:flags=lanczos[x];[x][1:v]paletteuse" $gifname
fi

echo Cleaning up...
rm -r "$tmpdir"

echo "Done"
